# Generated by Django 2.0.6 on 2018-06-21 07:07

from django.db import migrations, models
import rentahouse.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('AP', 'Apartamento'), ('CS', 'Casa'), ('CF', 'Condomínio fechado'), ('SB', 'Sobrado')], max_length=20)),
                ('qt_quartos', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5 ou mais')])),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('qt_vagas_garagem', models.PositiveIntegerField()),
                ('vl_aluguel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cep', models.CharField(max_length=9, validators=[rentahouse.core.validators.valida_cep])),
                ('logradouro', models.CharField(blank=True, max_length=80, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('dh_insercao', models.DateTimeField(auto_now_add=True)),
                ('dh_alteracao', models.DateTimeField(auto_now=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='anuncios/%Y/%m/%d/')),
            ],
        ),
    ]
