# Generated by Django 2.0.6 on 2018-06-17 14:19

from django.db import migrations, models
import rentahouse.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('P', 'Padrão'), ('V', 'Vila'), ('CF', 'Condomínio fechado')], max_length=20)),
                ('qt_quartos', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5 ou mais')])),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('qt_vagas_garagem', models.PositiveIntegerField(blank=True, default=0)),
                ('vl_condominio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('vl_aluguel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cep', models.CharField(max_length=9, validators=[rentahouse.core.validators.valida_cep])),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('dh_insercao', models.DateTimeField(auto_now_add=True)),
                ('dh_alteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
