# Generated by Django 2.0.6 on 2018-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='vl_condominio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
